sudo: required
#language: generic

services:
  - docker

before_install:
  - docker build -t macthenerd/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true macthenerd/docker-react npm run test
